
trigger:
- master

resources:
- repo: self

variables:
#  dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
  dockerRegistryServiceConnection: 'Local Registry'
#  imageRepository: '{{#toAlphaNumericString imageRepository 50}}{{/toAlphaNumericString}}'
  imageRepository: '$(Build.Repository.Name)'
  containerRegistry: '{{ containerRegistryConnection.Authorization.Parameters.loginServer }}'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: Local Agent
    steps:
    - task: Bash@3
      displayName: Maven build
      inputs:
        targetType: 'inline'
        script: |
          MAVEN_OPTS="-DproxyHost=172.17.0.1 -DproxyPort=3128" ./mvnw package
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests'
        path: 'manifests'