
trigger:
- master

variables:
  System.Debug: true
  dockerRegistryServiceConnection: 'Local Registry'
  localRegistryAddress: '172.17.0.1:5000'
  imageRepository: 'hello-world-app'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      name: Local Agent
    steps:
    - task: Bash@3
      displayName: Maven build
      inputs:
        targetType: 'inline'
        script: |
          MAVEN_OPTS="-DproxyHost=172.17.0.1 -DproxyPort=3128" ./mvnw package
          mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env|sort'

#    - task: PublishPipelineArtifact@1
#      inputs:
#        artifactName: 'manifests'
#        path: 'manifests'
