apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo
  labels: 
    app: spring-boot-demo
spec:
  selector:
    app: spring-boot-demo
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  labels:
    app: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
      - name: spring-boot-demo
        image: #{LocalRegistry}#/#{ImageName}#:#{tag}#
        ports:
        - containerPort: 8080 
