apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    version: "#{tag}#"
  annotations:
    kubernetes.io/change-cause: "Deploy version #{tag}#"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: #{containerRegistry}#/#{imageRepository}#:#{tag}#
        ports:
        - containerPort: 8080 
